version: '2'
services:
  #########################
  # CSIO Twilio audio only SHIM demo application
  #########################
  twilio-audio-shim-demo:
    build:
      context: ./../twilio-client-sample
    environment:
      TWILIO_ACCOUNT_SID: 'your_account_sid'
      TWILIO_API_KEY: 'your_api_key'
      TWILIO_API_SECRET: 'your_api_secret'
      APP_ID: 'your_app_id'
      APP_SECRET: 'your_app_secret'
      PORT: '5050'
      TARGET: "dev"
    ports:
      - "5050:5050"
    command: "python run.py"